name: publish-kedro-viz
description: This is a GitHub action to publish kedro viz static website on GitHub Pages
author: kedro-viz

branding:
  icon: share
  color: yellow

inputs:
  project_path:
    description: "Set your Kedro-project path to build the Kedro-Viz artifacts."
    required: false
    default: "."
  include_hooks:
    description: "Set whether to include hooks while creating your Kedro-project build artifacts."
    required: false
    default: false
  telemetry_consent:
    description: "Set your consent if you would like to participate in Kedro-Telemetry. Defaults to false"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install Kedro-Viz
      run: |
        python -m pip install --upgrade pip
        python -m pip install "kedro-viz>=7.1.0"
      shell: bash
    - name: Consent to the use of Kedro-Telemetry
      run: |
        cd ${{ inputs.project_path }}
        echo 'consent: ${{ inputs.telemetry_consent }}' > .telemetry
      shell: bash
    - name: Create build flags
      run: |
        flag=""
        if ${{ inputs.include_hooks }}; then
          flag="$flag --include-hooks"
        fi
        echo "build_flags=$flag" >> $GITHUB_ENV
      shell: bash
    - name: Create build directory
      run: |
        cd ${{ inputs.project_path }}
        if !(kedro viz build ${{ env.build_flags }} |& tee /dev/stderr | grep -i -q "Success!"); then
          exit 1
        fi
      shell: bash   
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "${{ inputs.project_path }}/build"
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
