# This workflow is used to test the GitHub action publish-kedro-viz

name: Test publish-kedro-viz

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Create a Kedro Project and install project dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "kedro>=0.19.3"
          kedro new --starter=spaceflights-pandas-viz --name=demo-project
          cd demo-project
          pip install -r requirements.txt
      - name: Deploy Kedro-Viz to GH Pages
        uses: ./
        with:
          project_path: "demo-project"
